language: java

jdk:
  - oraclejdk11

matrix:
  - jdk: oraclejdk11
    before_install:
      - rm "${JAVA_HOME}/lib/security/cacerts"
      - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean install
