version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-test
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: accounts
    ports:
    - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
