spring:
  application:
    name: bank-accounts
  datasource:
    url: jdbc:postgresql://localhost:5432/ACCOUNTS
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
