spring:
  application:
    name: bank-accounts
  datasource:
    url: jdbc:postgresql://localhost:5432/ACCOUNTS
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


restTemplate:
  configuration:
    connect-timeout: 5000
    read-timeout: 5000
nbp-api:
  url: http://api.nbp.pl/api/exchangerates/rates/a/usd
